CREATE TABLE `appSettings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`configName` varchar(120) NOT NULL DEFAULT 'Configuración principal',
	`isDefault` boolean NOT NULL DEFAULT true,
	`precioMultiple` int NOT NULL DEFAULT 99000,
	`precioJunior` int NOT NULL DEFAULT 69000,
	`precioSenior` int NOT NULL DEFAULT 69000,
	`precioParqueadero` int NOT NULL DEFAULT 8000,
	`ticketPromedioReferencia` int NOT NULL DEFAULT 500000,
	`minimoPersonasAmarillo` int NOT NULL DEFAULT 100,
	`minimoPersonasRojo` int NOT NULL DEFAULT 200,
	`minimoValorAmarillo` int NOT NULL DEFAULT 20000000,
	`minimoValorRojo` int NOT NULL DEFAULT 35000000,
	`diasUrgenciaAlta` int NOT NULL DEFAULT 2,
	`horasLeadCaliente` int NOT NULL DEFAULT 1,
	`scoreAltoThreshold` int NOT NULL DEFAULT 65,
	`calendarSyncEnabled` boolean NOT NULL DEFAULT false,
	`googleCalendarId` varchar(255),
	`emailAlertsEnabled` boolean NOT NULL DEFAULT false,
	`smsAlertsEnabled` boolean NOT NULL DEFAULT false,
	`alertEmailTo` varchar(320),
	`alertSmsTo` varchar(32),
	`updatedByUserId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `appSettings_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `leads` (
	`id` int AUTO_INCREMENT NOT NULL,
	`publicId` varchar(32) NOT NULL,
	`nombreCliente` varchar(160) NOT NULL,
	`telefono` varchar(32) NOT NULL,
	`correo` varchar(320) NOT NULL,
	`fechaVisita` bigint NOT NULL,
	`motivoVisita` text NOT NULL,
	`objecionPrincipal` text NOT NULL,
	`cantidadMultiple` int NOT NULL DEFAULT 0,
	`cantidadJunior` int NOT NULL DEFAULT 0,
	`cantidadSenior` int NOT NULL DEFAULT 0,
	`cantidadParqueadero` int NOT NULL DEFAULT 0,
	`precioMultiple` int NOT NULL DEFAULT 99000,
	`precioJunior` int NOT NULL DEFAULT 69000,
	`precioSenior` int NOT NULL DEFAULT 69000,
	`precioParqueadero` int NOT NULL DEFAULT 8000,
	`subtotalMultiple` int NOT NULL DEFAULT 0,
	`subtotalJunior` int NOT NULL DEFAULT 0,
	`subtotalSenior` int NOT NULL DEFAULT 0,
	`subtotalParqueadero` int NOT NULL DEFAULT 0,
	`totalPersonas` int NOT NULL DEFAULT 0,
	`valorTotal` int NOT NULL DEFAULT 0,
	`ticketPromedio` int NOT NULL DEFAULT 0,
	`scoreCantidad` int NOT NULL DEFAULT 0,
	`scoreValorTotal` int NOT NULL DEFAULT 0,
	`scoreTicketPromedio` int NOT NULL DEFAULT 0,
	`scoreUrgencia` int NOT NULL DEFAULT 0,
	`scoreRecencia` int NOT NULL DEFAULT 0,
	`scoreTotal` int NOT NULL DEFAULT 0,
	`prioridadBase` enum('gris','verde','amarillo','rojo') NOT NULL DEFAULT 'gris',
	`prioridad` enum('gris','verde','amarillo','rojo') NOT NULL DEFAULT 'gris',
	`prioridadExplicacion` text,
	`estadoLead` enum('nuevo','contactado','cotizado','seguimiento','ganado','perdido','pausado') NOT NULL DEFAULT 'nuevo',
	`canalOrigen` enum('whatsapp','instagram','facebook','web','llamada','referido','otro') NOT NULL DEFAULT 'otro',
	`agenteUserId` int,
	`agenteResponsable` varchar(160),
	`fechaIngresoLead` bigint NOT NULL,
	`fechaLimiteGestion` bigint,
	`ultimaGestion` bigint,
	`proximaAccion` text,
	`notasInternas` text,
	`calendarEventId` varchar(255),
	`calendarEventUrl` text,
	`calendarSyncStatus` enum('disabled','pending','synced','error') NOT NULL DEFAULT 'disabled',
	`calendarSyncMessage` text,
	`alertPending` boolean NOT NULL DEFAULT false,
	`alertLastChannel` varchar(32),
	`alertLastMessage` text,
	`lastAlertAt` bigint,
	`closedAt` bigint,
	`createdByUserId` int NOT NULL,
	`updatedByUserId` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `leads_id` PRIMARY KEY(`id`),
	CONSTRAINT `leads_publicId_unique` UNIQUE(`publicId`)
);
--> statement-breakpoint
ALTER TABLE `appSettings` ADD CONSTRAINT `appSettings_updatedByUserId_users_id_fk` FOREIGN KEY (`updatedByUserId`) REFERENCES `users`(`id`) ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `leads` ADD CONSTRAINT `leads_agenteUserId_users_id_fk` FOREIGN KEY (`agenteUserId`) REFERENCES `users`(`id`) ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `leads` ADD CONSTRAINT `leads_createdByUserId_users_id_fk` FOREIGN KEY (`createdByUserId`) REFERENCES `users`(`id`) ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `leads` ADD CONSTRAINT `leads_updatedByUserId_users_id_fk` FOREIGN KEY (`updatedByUserId`) REFERENCES `users`(`id`) ON DELETE restrict ON UPDATE no action;